//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.EquipmentCategories = new HashSet<EquipmentCategory>();
            this.EquipmentSpecifications = new HashSet<EquipmentSpecification>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double ProductionRunTime { get; set; }
        public int ProductionCapacity { get; set; }
        public int RunCapacity { get; set; }
        public double FirstPassYield { get; set; }
        public System.TimeSpan ChangeOrderTime { get; set; }
        public string ProductionLine { get; set; }
        public System.TimeSpan DownTime { get; set; }
        public double OperatorCount { get; set; }
        public int WorkStationId { get; set; }
    
        public virtual WorkStation WorkStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentCategory> EquipmentCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentSpecification> EquipmentSpecifications { get; set; }
    }
}
