//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessScheduling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Molding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Molding()
        {
            this.EquipmentSpecifications = new HashSet<EquipmentSpecification>();
            this.EquipmentCategories = new HashSet<EquipmentCategory>();
        }
    
        public int Id { get; set; }
        public int PartId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Desciption { get; set; }
    
        public virtual Part Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentSpecification> EquipmentSpecifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentCategory> EquipmentCategories { get; set; }
    }
}
