//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessScheduling.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SupplyEntities : DbContext
    {
        public SupplyEntities()
            : base("name=SupplyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyContact> CompanyContacts { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Line> Lines { get; set; }
        public virtual DbSet<WorkStation> WorkStations { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<PlanProduct> PlanProducts { get; set; }
        public virtual DbSet<WorkStationType> WorkStationTypes { get; set; }
        public virtual DbSet<Molding> Moldings { get; set; }
        public virtual DbSet<EquipmentSpecification> EquipmentSpecifications { get; set; }
        public virtual DbSet<EquipmentCategory> EquipmentCategories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderSection> OrderSections { get; set; }
    }
}
